language: node_js
node_js:
  - stable
  - "4.1"
  - "0.12"
  - "0.11"
os:
  - linux
script: "npm run-script test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"